# Generated by Django 4.2.6 on 2024-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acitivityrecord',
            name='assignee',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
